### ISSUE TITLE
Images Appear as Attachment, Recipient Doesn't Receive it

### ISSUE THREAD

**Issue by ToddAlvord** [airmessage/airmessage-android#31]
Server Version: 3.4.1
App Version: 3.3.8

I'm no longer able to send images from my android.

On my end, this is what I see in Messages
![image](https://user-images.githubusercontent.com/9203805/158281131-2b23ad7c-bb6d-4a70-b3e3-1b6ea60b9629.png)

On the recipients end they only received the text `Testing`

**Comment by CSab6482** [comment]
Is your macOS device running Monterey? Unfortunately I don't have a solution to offer, just the fact that sending iMessage attachments through AppleScript is either partially or fully broken/no longer available on macOS Monterey.

**Comment by tagavari** [comment]
Thanks for the report! This issue is resolved in the alpha version of AirMessage Server. I'm looking to release it to the beta channel shortly, though if you want to try it now, you can download it from here: https://github.com/airmessage/airmessage-server-next/releases

**Comment by ToddAlvord** [comment]
Just installed the alpha and tried sending an image and it worked! Thanks @tagavari
