### ISSUE TITLE
[Feature Request] Ability to backup SMS messages

### ISSUE THREAD

**Issue by sethbaird01** [airmessage/airmessage-android#35]
As far as I can tell there's no way to backup "green" messages in AirMessage meaning I can't reinstall or transfer to another device - would be nice to have a csv or other arbitrary format export/backup option.

Something like this would be very helpful if it meant we could migrate messages to a different messaging app

**Comment by sethbaird01** [comment]
A feature like this would be very helpful if it meant we could migrate messages to a different messaging app

**Comment by Zyonse** [comment]
This should already be handled by Android's default backup system

**Comment by sethbaird01** [comment]
Ah okay, thanks. I'm new to Android so didn't know about this.
