### ISSUE TITLE
No spell check underlines

### ISSUE THREAD

**Issue by mike-lloyd03** [airmessage/airmessage-android#57]
Misspelled words are not underlined in red only in AirMessage. I can still tap on misspelled words for spelling suggestions but it's easy to miss misspelled words without the underline. Using any of the following keyboards produces the same result:

- Gboard
- OpenBoard
- Florisboard Beta

System spell check is enabled and spell check works in other apps.

**Comment by tagavari** [comment]
Thank you for reporting this! Spell check will be working properly in the next major release:

![Screenshot_20221116-111609~2.png](https://user-images.githubusercontent.com/13751213/202235510-26e5f3ae-3435-4801-9cba-29b4e147ac37.png)

**Comment by mike-lloyd03** [comment]
Awesome thanks!
