### ISSUE TITLE
[Bug] AirMessage Beta doesn't work on OneUI 3

### ISSUE THREAD

**Issue by CSab6482** [airmessage/airmessage-android#6]
u/Ok_Necessary_1306 made a post about this [here](https://www.reddit.com/r/AirMessage/comments/mif5eo/is_anyone_else_experiencing_problems_trying_to/) with an S21 Ultra. Below is the image from their post. u/andrewapicture had the same issue on their S21.
![qg3540sqnpq61](https://user-images.githubusercontent.com/53708281/116934019-60f5dd00-ac32-11eb-89ca-153dd795264a.jpg)

I also made a [post](https://www.reddit.com/r/AirMessage/comments/lxsu67/unable_to_set_up_app_server_31_android_314/) about this issue with my S10e on OneUI 3, however, I have since downgraded to OneUI 2.5 where AirMessage beta works perfectly. Below is a copy and paste of my post.
> I tried to set up the AirMessage beta with manual IP/port forwarding, but I was unable to do so. Below is a photo/video of my issue with all personal information removed.
>
> At first, I didn't know what the problem, was, so I attempted to use the stable server and Android app. I was prompted to install the JDK, so I did that, and then the stable app worked. Then, I tried the beta app one more time, but I still received the same error (I switched between stable and beta about 5 times, and I tried using my public and private IP addresses instead of my DDNS address, and nothing worked). Does anyone have any thoughts?
![1g7w8h52a2l61](https://user-images.githubusercontent.com/53708281/116934025-62bfa080-ac32-11eb-860a-12408a28f0a8.jpg)
https://www.reddit.com/link/lxsu67/video/16yupel7a2l61/player

**Comment by tagavari** [comment]
I was actually able to recreate this bug once on my device (Pixel 5) out of the blue, and it turns out that it was an issue with the app being unable to modify its encrypted shared preferences to write the new server values.

AirMessage uses [Android Jetpack's Security](https://developer.android.com/jetpack/androidx/releases/security) library for encrypted storage. The current beta versions uses a release candidate, but it looks like a stable version is finally available. I'll include this dependency update in the next beta version.

**Comment by tagavari** [comment]
I found out that the Security library creates a shared preferences file that must be in sync with the device's local keychain, and will error out if there's a mismatch. This file not marked as excluded from Android's Auto Backup, so if you installed the app on a second device or uninstalled and reinstalled the app on the same device, you would end up with an invalid shared preferences file.

I've updated the backup rules with [commit fef35bf](https://github.com/airmessage/airmessage-android/commit/fef35bf8395e6947e34e60df75ff5dcd397340f7), and it's included in release 3.1.6 which is out today. If you're still running into this issue, could you let me know if this update fixes it for you?

**Comment by CSab6482** [comment]
I have since downgraded to OneUI 2.5, so I won't be able to test it unless I upgrade. I'll make a comment on u/Ok_Necessary_1306's post to see if they can test it

**Comment by tneotia** [comment]
FWIW airmessage cloud works fine on OneUi 3, haven't had any issues on my S10+.

**Comment by CSab6482** [comment]
> FWIW airmessage cloud works fine on OneUi 3, haven't had any issues on my S10+.

Thank you for confirming that it is fixed!

**Comment by tneotia** [comment]
I wouldn't close this as I use airmessage cloud rather than the manual IP method. Just wanted to point out that the cloud version is working fine.

**Comment by CSab6482** [comment]
Oh shoot okay. If you could test the manual configuration (like, no port forwarding just with your Mac's internal IP), let me know, but it's okay if you can't. Thanks for the heads up.

**Comment by tneotia** [comment]
Yes later today I'll try it out and report back :)

**Comment by tneotia** [comment]
Just tested via manual config and it is working flawlessly using the latest server and client betas.
