### ISSUE TITLE
airmessage.org SSL Certificate Expired

### ISSUE THREAD

**Issue by Falcc** [airmessage/airmessage-android#64]
Hello - heads up, the airmessage.org SSL certificate expired.
My local airmessage server also says "no internet connection" - which it wasn't previously. I'd assume it's trying to hit airmessage.org or something and because the certs expired, it's being rejected?
Airmessage is fully down for me now.

**Comment by Falcc** [comment]
![2023-11-01 11_26_09-Certificate for _ airmessage org — Mozilla Firefox](https://github.com/airmessage/airmessage-android/assets/79353170/076df63a-3b2f-4572-8b7e-10064c6deff7)

**Comment by tagavari** [comment]
Thanks for the heads-up! All certificates have been updated.

**Comment by Falcc** [comment]
Seems to have resolved the server's issue with access to internet. Android app is still claiming "No internet connection" specifically.
Tried phone restart, tried clear app cache, tried clear app cache and app data. On trying to re-login I'm still hitting "No internet connection".

**Comment by zmalter99** [comment]
Same here. Haven't found a resolution yet.

**Comment by working-name** [comment]
> Thanks for the heads-up! All certificates have been updated.

woah! This is not abandonware?!

**Comment by Falcc** [comment]
This is resolved now. It's all working.
@tagavari  - it does beg the questions:
1. What data gets sent to and from airmessage.org, given it's a locally hosted service?
2. If no data other than a "internet connectivity check" is sent, could that check be replaced with something more reliable such as 8.8.8.8?

**Comment by tagavari** [comment]
While AirMessage does rely on a Mac for iMessage functionality, most users also use AirMessage's proxy servers, which handle maintaining a connection between your Android phone / web browser and Mac, and avoid the hassle of port forwarding.

This is what happens when you sign in to AirMessage with a Google account. If instead you set up a manual / direct connection, you'll end up with a regular self-hosted service like you're thinking of.

**Comment by Falcc** [comment]
> While AirMessage does rely on a Mac for iMessage functionality, most users also use AirMessage's proxy servers, which handle maintaining a connection between your Android phone / web browser and Mac, and avoid the hassle of port forwarding.
> 
> This is what happens when you sign in to AirMessage with a Google account. If instead you set up a manual / direct connection, you'll end up with a regular self-hosted service like you're thinking of.

Got it. Thanks.
What data is passed through the proxy servers and what data is stored?
(EG: Are messages traversing through the proxy server clear text? Are they encrypted end to end?)

**Comment by tagavari** [comment]
@Falcc [It depends on how you have your server configured.](https://airmessage.org/blog/end-to-end-encryption-across-all-of-airmessage) If you set a password in AirMessage Server under Preferences... > Edit Password, that password will be used end-to-end to encrypt all message content sent through the proxy servers, as well as Google's push notification servers. If you don't set a password, your data is not end-to-end encrypted, but is still encrypted in transit.

Any information passed through the proxy server is treated as opaque, and isn't saved or logged. The only data that's recorded is installation identifiers and FCM tokens for message-routing purposes.

If you'd like to see this in the source code, you can see the logic [here in the Android app](https://github.com/airmessage/airmessage-android/blob/main/app/src/full/java/me/tagavari/airmessage/connection/comm5/ProxyConnect.java), as well as a [previous implementation of AirMessage's proxy servers](https://github.com/airmessage/airmessage-connect-java).

**Comment by Falcc** [comment]
@tagavari  Thanks for the clarification. I'll close this issue now that it's all resolved.
