### ISSUE TITLE
App Crashes with Contacts Access Enabled

### ISSUE THREAD

**Issue by ben-ihelputech** [airmessage/airmessage-android#65]
## Device Details

Pixel 5a
Android 14
AirMessage 3.5.2

## Steps to Reproduce

1. Download the latest version of AirMessage on a fresh of Android.
2. Connect to AirMessage server. (I tried both connecting with a Google account and direct connect via hostname and password)
3. On the AirMessage homescreen, click `Enable` on the banner that prompts `Allow access to contacts to show names and pictures`.
4. Send or receive a message from a number that is not in your contacts list. The app will crash and the message may not be sent, or appear multiple times. However, when a number is saved to the device contacts, the app will not crash. 

I tried the same thing on an identical Pixel 5a running LineageOS, and whenever contacts are enabled, it does not crash the app, but message will not send. Disabling Contacts in the Settings permissions menu for the app resolves the issue.

## Desired Behavior

The ability to send and receive messages, even if the number is not in the device contacts.

**Comment by tagavari** [comment]
Thank you for the report! This bug will be resolved in v4.0.0, which will be made available soon.

**Comment by svanhoutte** [comment]
@tagavari hi, any update on the release date for version 4.0.0?
