### ISSUE TITLE
[Bug] Duplicated Messages

### ISSUE THREAD

**Issue by CSab6482** [airmessage/airmessage-android#7]
u/iEatPremiumRice reported this issue in [this post](https://www.reddit.com/r/AirMessage/comments/lx8ne3/is_he_right_but_i_love_airmessage/), and below is the photo from their post.
![81n5dud5rwk61](https://user-images.githubusercontent.com/53708281/116934697-4c661480-ac33-11eb-8f3a-11d04d210e99.jpg)

u/cultsuperstar also reported this issue in [an older post](https://www.reddit.com/r/AirMessage/comments/jepjfn/duplicate_messages_airmessage_302_beta_server_30/), and below is their screenshot.
![E1AuOR0](https://user-images.githubusercontent.com/53708281/116934701-4cfeab00-ac33-11eb-9a30-de299394183d.jpeg)

**Comment by tagavari** [comment]
The latest beta version of the Android app 3.1.5 receives messages over FCM instead of over the network, which does away with the logic where I think this bug would have most likely been. Do you know if this issue is still present?

**Comment by CSab6482** [comment]
I personally never experienced this issue, so I will close this ticket. I will shortly update my comment on issue #8.

**Comment by Zyonse** [comment]
This is still happening on latest beta
