### ISSUE TITLE
[Bug] Duplicated Tapbacks

### ISSUE THREAD

**Issue by CSab6482** [airmessage/airmessage-android#8]
I'm not sure if this bug occurs for the same reason as issue #7, so I opened a separate ticket just in case. I originally reported this in my reddit post [here](https://www.reddit.com/r/AirMessage/comments/lqmmf3/bug_tapbacks_are_duplicated_android_app_version/), and below is a copy and paste of that post.

> I thought it was strange to see that the messages had four tapbacks when the chat only has three people, so then I checked the details and saw the tapbacks were duplicated. My phone is on Android 10 (OneUI 2.5) and my Mac is on macOS 10.14.6 Mojave.
> ![lzmpouiu89j61](https://user-images.githubusercontent.com/53708281/116935081-d910d280-ac33-11eb-8a91-d2683463d60e.jpg)
> ![agfa3viu89j61](https://user-images.githubusercontent.com/53708281/116935098-dd3cf000-ac33-11eb-8f04-9a202675d66d.jpg)
> ![qoiytwiu89j61](https://user-images.githubusercontent.com/53708281/116935106-e201a400-ac33-11eb-8023-75f554bcfae5.jpg)
> ![d0znq2ju89j61](https://user-images.githubusercontent.com/53708281/116935131-ec23a280-ac33-11eb-8b1b-9663963eeab9.png)
> ![lxurn1ju89j61](https://user-images.githubusercontent.com/53708281/116935147-f2198380-ac33-11eb-9fa5-b978995d627b.png)

Tagavari then commented
> Thank you for reporting this issue. I'll have to do a bit of troubleshooting this weekend, I'll see if I can get it fixed!

To which I replied
> This happened after a message sync so that may be related

**Comment by tagavari** [comment]
Do you still have this issue on the latest version of the Android app (3.1.5)? There were some changes made to how tapbacks are received, most notably when a participant changes or removes a tapback message. There were also changes made to how messages are received over the network in this version.

**Comment by CSab6482** [comment]
Op, I have been using [this link](https://1drv.ms/f/s!At_N4m-8Bsk4l-QOrcyhG2JpWLoERw) instead of the new [releases link](https://github.com/airmessage/airmessage-android/releases). I'll give it a go and let you know!

**Comment by CSab6482** [comment]
My message history doesn't scroll up far enough for me to see these original messages, but as far as I can see, all of the tapback counts are accurate in version 3.1.5, so I will close this. Thank you!
